baseURL = "http://example.org/"
languageCode = "en-us"
theme = "hyde"
title = "Smithlabs Blog"


[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/username/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
  ]

[params]
layoutReverse = true
